### ISSUE TITLE
Shrubhill Development 

### ISSUE THREAD

**Issue by chrisfleming** [osm-scotland/mappingedinburgh-issues#28] opened 2018-11-15 22:33 UTC
https://www.openstreetmap.org/note/983619#c3344767

**Comment by donaldrnoble** [comment] 2019-12-30 20:15
Have mapped development as of November - still ongoing

**Comment by donaldrnoble** [comment] 2019-12-30 20:21
duplicate of #18

**Closed as completed by donaldrnoble** 2019-12-30 20:21 UTC
